import GlobalCssPriority from "@/components/GlobalCssPriority"
import SuspenseLayout from "@/components/SuspenseLayout"
import { ThemeProvider } from "@mui/material"
import { Metadata } from "next"
import { Inter } from "next/font/google"
import { ReactNode } from "react"
import "./globals.css"
import CTS from "./utils/constants"
import { theme } from "./utils/mui-theme-config"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: CTS.DOMAIN_BRAND,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale }
}: {
  children: ReactNode;
  params: { locale: string };
}) {

  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <meta name="msapplication-TileColor" content="#231f20"> */}
        {/* <meta name="theme-color" content="#231f20"> */}
        <meta
          name="format-detection"
          content="telephone=no, date=no, email=no, address=no"
        />
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link
          rel="preconnect"
          crossOrigin="anonymous"
          href="https://fonts.googleapis.com"
        />
        <link
          rel="preconnect"
          crossOrigin="anonymous"
          href="https://fonts.gstatic.com"
        />
        <link
          rel="stylesheet"
          crossOrigin="anonymous"
          href="https://fonts.googleapis.com/css2?family=Manrope&display=swap"
        />
      </head>
      <body id="__next" className={inter.className}>
        <GlobalCssPriority>
          <ThemeProvider theme={theme}>
            <div suppressHydrationWarning={true}>
              <SuspenseLayout>{children}</SuspenseLayout>
            </div>
          </ThemeProvider>
        </GlobalCssPriority>
      </body>
    </html>
  );
}
